### ISSUE TITLE
shipit_code_coverage: Tasks are aborted because "states could not be created successfully"

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#1015]
[taskcluster:error] Task was aborted because states could not be created successfully. Error: Error calling 'link' for taskclusterProxy : Error: (HTTP code 500) server error - connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused"  | Error: Error calling 'link' for localLiveLog : Error: (HTTP code 500) server error - connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused"

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1450901

**Comment by marco-c** [comment]
@garbas could this be a regression from #928?

**Comment by garbas** [comment]
@marco-c it might be connected, but this is probably a problem on taskcluster side since the error is intermittent. I guess services and is an early adopter of taskcluster and sadly we are paving a road for other teams since we are discovering this bugs.

I will comment on the issue above with the changes that happen last week in provisioner, just in case it is related.

**Comment by marco-c** [comment]
Closing since it's very likely not a problem on our side.
