### ISSUE TITLE
shipit_pulse_listener: Deployment not working

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#1203]
The last deployment was made on Heroku on May 8. So there are at least two deployments missing (update to v40, dependencies update).

CC @garbas

**Comment by jankeromnes** [comment]
Blocks #1166.

**Comment by garbas** [comment]
oh my, there was a change in how docker<->heroku work
it is not enough to only push the docker image. now you need to curl to trigger a release

https://devcenter.heroku.com/articles/container-registry-and-runtime#releasing-an-image 

From the look of it last release was done on May 8th, for any of the heroku projects

**Comment by jankeromnes** [comment]
Good catch!

> it is not enough to only push the docker image. now you need to curl to trigger a release

I think you can set up a web hook on Docker Hub itself, or maybe you can `curl` from the same CI you use to auto-build the docker images?

**Comment by garbas** [comment]
The problem was fixed in #1204 and tested (successfully) on staging, but we still need to decide if we want to uplift this fix to production or just move ahead and cut new release.

Regarding releng stuff we can safely just cut new release.
@marco-c @La0: Do you think we need to uplift this fix to production?

**Comment by La0** [comment]
Closing this issue, since v41 fixed it, and Pulse listener got updated.
