### ISSUE TITLE
Observatory grade is too low to go live 

### ISSUE THREAD

**Issue by hwine** [mozilla-releng/services#141]
legacy scores a 'D', but we should do better. 'B' should be our low bar. [Report](https://observatory.mozilla.org/analyze.html?host=mozilla-releng.net)

**Comment by garbas** [comment]
for the backend, i need to use something like https://github.com/GoogleCloudPlatform/flask-talisman
for the frontend, I need to set headers in CloudFront

**Comment by garbas** [comment]
@hwine It looks like AWS does not support setting up custom headers at the moment. looks like we would should either move away from it or wait until they implemented it. it looks (from many discussions in the forum) that it is on their agenda, but there is no clear deadline.

how strong do you feel this should be a blocker for going on with going live with treestatus?

**Comment by garbas** [comment]
@ccooper maybe you also want to help me decide here. "ignoring" csp for now (until amazon supports it) or moving our frontend code (static content) to somewhere else.

I would personally vote for "ignoring" for the time being since I'm already really behind the schedule.

Also this is not a service that you would be able to explore using XSS since it is all static html/css/js. But I see it more as a nice thing to have, but not a blocker.

**Comment by garbas** [comment]
just implemented CSP via <meta> tags
