### ISSUE TITLE
don't require bugzilla login to use ship it

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#223]
It looks to me like the shipit_frontend app cannot be used without logging into Bugzilla. Even after authenticating with Taskcluster, nothing is shown to me, and the drop down in the top right suggests I should login to Bugzilla.

I imagine Bugzilla is required to work with the uplift_bot, but I don't think it's used for other parts of shipit?

**Comment by garbas** [comment]
Bugzilla is only a dependency for uplift dashboard.

There is no UI for other parts other then uplift at this point.
If you see "Home" then this is it.

Since only uplift is been developed I left @La0 decide how to structure it and there is already plan to move this "Login to Bugzilla" into the uplift dashboard view. Because of Elm this is not a big change.

I consider this a no issue, since there is nothing else then uplift at this point.
