### ISSUE TITLE
shipit_code_coverage: appears to return lots of empty strings:

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-releng/services#654]
For each changeset, the UI continue to say "We're waiting for coverage data from the backend.", and it seems to be a result of the backend sending an empty string.  As an example:

https://uplift.shipit.staging.mozilla-releng.net/coverage/changeset/f38e89957937e4ef742302cd31927a077b3d3ba9

Is this empty string an error, or a way of saying there is nothing available?

**Comment by klahnakoski** [comment]
Of course, now the example returns something. :/

**Comment by klahnakoski** [comment]
Maybe have shipit return something that looks like a "please wait"?

**Comment by marco-c** [comment]
This is on purpose since when we introduced the background worker. The empty string means that the backend has not calculated data for that changeset yet and is queueing the job.
The status code of the request is 202, so the frontend knows that it needs to perform the request again (this is what "Pending" in the frontend means).

**Comment by klahnakoski** [comment]
Thank you!  Now I know what 202 means.
