### ISSUE TITLE
shipit_static_analysis: add mozlint support

### ISSUE THREAD

**Issue by ahal** [mozilla-releng/services#673]
The mozreview/phabricator static analysis bot should run |mach lint| and post those results to the review as well.

I'm not sure how this is implemented, but assuming it runs from within a source-tree, you can get structured results by running:

    ./mach lint --format json <path/to/file>

**Comment by jankeromnes** [comment]
Great suggestion! Thanks a lot for filing this issue. Using `./mach lint` would allow our bot to also catch issues in JS, Python and Web Platform Test files.

1. Do you know if we can get `./mach lint` to also output fix suggestions? Our bot sometimes adds suggested fixes to its comments, like in [this review](https://reviewboard.mozilla.org/r/174110/#review192124), and they can be really helpful.

2. I'm having trouble getting `./mach lint` to complain at all. I've appended `var a = null; a.nope(); a /= 0` to `devtools/client/menus.js`, but `./mach lint devtools/client/*` still says `? 0 problems (0 errors, 0 warnings)`. Could you please help me get it to complain about something?

**Comment by ahal** [comment]
Yeah, you'll want to use the `hint` field that shows up in the json output:
https://dxr.mozilla.org/mozilla-central/source/python/mozlint/mozlint/result.py#32

However I think only `eslint` currently fills this out, so you'll need to check if the hint exists or not before adding it to your format.

**Comment by ahal** [comment]
About your troubles getting it to run, try just running `./mach lint devtools/client` (without the glob). That will run all relevant files under that directory, as determined by mozlint + eslint.

**Comment by ahal** [comment]
Actually, I think those are just not things that `eslint` detects. Remember it is just linting source files, not running anything. Try adding an unused variable or missing semicolon or the like. E.g, adding `var foo` should spit out both `no-unused-variables` and `semi` errors.

**Comment by jankeromnes** [comment]
Ah, indeed, thanks for the explanation!

@La0 would you be interested in working on adding `./mach lint` to our bot? It would allow us to also catch issues in JS, Python and Web Platform Test files. I'll tentatively assign you on this issue. :)

Calling `./mach lint` automatically installs dependencies on first call (at least ESLint), but maybe we'll want to install them all beforehand into our Nix image, and use the `-b` parameter to specify binary locations.

Example outputs, when you add `var foo` (without semicolon) in a JS file like `devtools/client/menus.js`, you get this:

```
$ ./mach lint devtools/client/menus.js
/home/user/firefox/devtools/client/menus.js
  39:5  error  'foo' is defined but never used.  no-unused-vars (eslint)
  39:8  error  Missing semicolon.                semi (eslint)

? 2 problems (2 errors, 0 warnings)
```

Or, maybe more useful for us, in JSON format (FYI there are other formats like `compact`, `treeherder` and `unix`):

```
$ ./mach lint --format json devtools/client                                                                             
{
  "/home/user/firefox/devtools/client/menus.js": [
    {
      "hint": null,
      "column": 5,
      "level": "error",
      "linter": "eslint",
      "rule": "no-unused-vars",
      "source": "var foo",
      "lineno": 39,
      "path": "/home/user/firefox/devtools/client/menus.js",
      "message": "'foo' is defined but never used.",
      "lineoffset": null
    },
    {
      "hint": {
        "text": ";",
        "range": [
          1762,
          1762
        ]
      },
      "column": 8,
      "level": "error",
      "linter": "eslint",
      "rule": "semi",
      "source": "var foo",
      "lineno": 39,
      "path": "/home/user/firefox/devtools/client/menus.js",
      "message": "Missing semicolon.",
      "lineoffset": null
    }
  ]
}
```

Maybe this could be translated to a MozReview comments like these:

- `Error: 'foo' is defined but never used. [eslint: no-unused-vars]`
- `Error: Missing semicolon. [eslint: semi]`

Additionally, I think we can convert the `hint` parameter for the second error to something like this:

```
var foo
       ^
       ;
```

(But unfortunately, the `range` indicators seem to be in "number of chars since beginning of file" instead of "line number + column").

**Comment by ahal** [comment]
Note: lineno + column is in the main data structure

Plus, I think that { 'text': ..., 'range': ... } `hint` format is an eslint specific thing. I didn't realize it was doing that, we probably need to agree on a standard format for the `hint` field. So far eslint is the only linter that even populates the `hint` field, but we could modify some of the others to do so as well.

In general, you'll need to be pretty flexible here. E.g some linters can't even provide a column.

**Comment by La0** [comment]
Mozlint is used in production since several weeks.
