### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by jdashg** [mozilla-releng/services#698]
**MozReview URL:** 
https://reviewboard.mozilla.org/r/194786/#review199848

**Problem:** 
"Warning: The 'empty' method should be used to check for emptiness instead of 'size' [clang-tidy: readability-container-size-empty]"

This warning is not reflected in our style guide[1], and so should be removed until such time as it becomes a recommendation.

[1]: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style

**Comment by abpostelnicu** [comment]
The name of checker might be misleading, but that checker also addresses a performance issue, since the size method is not guaranteed be of constant-time function.
More than this for many containers the signature of size() might be like this:

`size_type size() const;`

And you can see that size_type can be of any integer type. So i strongly suggest to use empty(), that leaves more room for the compiler to make performance adjustments.

For further reading on this matter i suggest: https://clang.llvm.org/extra/clang-tidy/checks/readability-container-size-empty.html

**Comment by jdashg** [comment]
`size()` is constant time for everything (except `std::list` before c++11), as far as I can tell. (from cplusplus.com and a quick peek at the c++14 working draft)

I don't see this being much of a performance concern either, and frankly I'd be a little surprised if most `empty()` implementations don't just `return !size();`.

Regardless, if you want to warn on it, integrate it into the style guide.

**Comment by abpostelnicu** [comment]
I totally agree with you, I've tried to look for a container where size was not time-constant starting with cpp11 and there aren't
I've updated the coding style guidelines: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#CC_practices

**Comment by jankeromnes** [comment]
This warning is now reflected [in our style guide](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#CC_practices), so it can remain enabled in clangbot and this issue is now fixed. Thanks all!
