### ISSUE TITLE
shipit_uplift: Split uplift and coverage backend

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#885]
The coverage backend has grown a lot and now it makes sense to split them in two separate projects.

`shipit_code_coverage_backend` I guess.

**Comment by marco-c** [comment]
Or `code_coverage_backend` without `shipit_`. We could also rename `shipit_code_coverage` to `code_coverage_task` or something like this.

**Comment by marco-c** [comment]
I will do this once we have the simpler way to create a new project. CC @garbas

**Comment by garbas** [comment]
depending on #191

**Comment by marco-c** [comment]
@La0 do you want to take care of this?

**Comment by garbas** [comment]
since there is no documentation i guess i can write here how to use `./please create`

- templates are stored in `nix/templates/` and are normal [cookiecutter templates](https://cookiecutter.readthedocs.io/en/latest/tutorial2.html)
- there is currently only one template called `backend-json-api` and yes i agree it is a horrible name, i'm just out of good ideas for naming
- to create a new project you run for example `./please create backend-json-api shipit_bot_code_coverage`, that will:
  - create a project in `src/shipit_bot_code_coverage`
  - run `pypi2nix` to pin all of the dependencies so that you can immediately start using `./please` command
 you will need to manually configure projects deployment in `lib/please_cli/please_cli/config.py`, but `./please shell <project>` should work OOTB

**Comment by La0** [comment]
@marco-c @sylvestre I'll start working on the new code coverage backend next week.
